// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:f7196548-0cd6-4416-8e29-a32e4d2a3100",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_i6OUrM2I5",
    "aws_user_pools_web_client_id": "njngb6essgo8plep969pq7l05",
    "oauth": {}
};


export default awsmobile;
